CREATE TABLE "ESPECIALIDADES" (
	"id"	INTEGER,
	"nome"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
)

CREATE TABLE "FORMACAO" (
	"id"	INTEGER,
	"ano"	INTEGER NOT NULL,
	"id_especialidade"	INTEGER NOT NULL,
	"id_instituicao"	INTEGER NOT NULL,
	"quantidade"	INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY("id_especialidade") REFERENCES "ESPECIALIDADES"("id") ON DELETE RESTRICT,
	FOREIGN KEY("id_instituicao") REFERENCES "INSTITUICAO"("id") ON DELETE RESTRICT
)

CREATE TABLE "INSTITUICAO" (
	"id"	INTEGER,
	"nome"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
)